#Regression

1. What is Simple Linear Regression?
   - Simple Linear Regression is a statistical and machine learning method used to understand and model the relationship between one independent variable (X) and one dependent variable (Y) by fitting a straight line to the data.
   - It assumes that the dependent variable changes linearly with the independent variable.
   - Mathematical Equation: Y=mX+c

2. What are the key assumptions of Simple Linear Regression?
   - What are the key assumptions of Simple Linear Regression
   - The residuals (errors) should be independent of each other.
   - The variance of errors should be constant for all values of X.
   - The residuals should be normally distributed.
   - Since there is only one independent variable, multicollinearity does not occur.
   - The average of residuals should be zero.

3. What does the coefficient m represent in the equation Y=mX+c?
   - It shows how much Y changes when X increases by 1 unit. It indicates the direction and strength of the relationship between X and Y.
   - m > 0 → Positive relationship, m < 0 → Negative relationship, m = 0 → No linear relationship

4. What does the intercept c represent in the equation Y=mX+c?
   - It is the point where the regression line crosses the Y-axis. It shows the starting or baseline value of the dependent variable.

5. How do we calculate the slope m in Simple Linear Regression?
   - Formula to Calculate Slope (m): 𝑚 =∑(𝑥−𝑥ˉ)(𝑦−𝑦ˉ)/∑(𝑥−𝑥ˉ)^2
   - Slope m = covariance(X, Y) / variance(X)

6. What is the purpose of the least squares method in Simple Linear Regression?
   - To minimize the total error between actual values and predicted values. More precisely, it minimizes the sum of the squares of the residuals.
   - The least squares method gives: Best values of m and c, Most accurate predictions under linear assumptions.

7. How is the coefficient of determination (R²) interpreted in Simple Linear Regression?
   - Coefficient of Determination (R²) indicates the proportion of variance in the dependent variable (Y) that is explained by the independent variable (X). Its value ranges from 0 to 1, where a higher value means a better model fit.

8. What is Multiple Linear Regression
   - Multiple Linear Regression is a statistical method used to model the relationship between one dependent variable (Y) and two or more independent variables (X₁, X₂, …, Xₙ) by fitting a linear equation.
   -Equation: Y=b0​+b1​X1​+b2​X2​+⋯+bn​Xn​
   - It helps in predicting Y and understanding the effect of each independent variable on Y while keeping others constant.

9. What is the main difference between Simple and Multiple Linear Regression?
   - The main difference is the number of independent variables used:       1. Simple Linear Regression uses one independent variable to predict the dependent variable.
   2. Multiple Linear Regression uses two or more independent variables to predict the dependent variable.

10. What are the key assumptions of Multiple Linear Regression?
    - Key assumptions of Multiple Linear Regression are:  
    1. Linearity – The relationship between independent variables and the dependent variable is linear.
    2. Independence of errors – Residuals are independent of each other.
    3. Homoscedasticity – Constant variance of errors across all levels of predictors.
    4. Normality of errors – Residuals are normally distributed.
    5. No multicollinearity – Independent variables should not be highly correlated.

11. What is heteroscedasticity, and how does it affect the results of a Multiple Linear Regression model?
    - Heteroscedasticity occurs when the variance of residuals is not constant across all levels of independent variables.
    - Effect on Multiple Linear Regression:                               
    1. Coefficient estimates remain unbiased
    2. Standard errors become incorrect/
    3. Leads to unreliable hypothesis tests and confidence intervals
    4. Can result in wrong conclusions about variable significanc

12. How can you improve a Multiple Linear Regression model with high multicollinearity?
    - To improve a Multiple Linear Regression model with high multicollinearity, you can:
    1. Remove highly correlated variables to reduce redundancy.
    2. Combine variables (e.g., using feature engineering or PCA).
    3. Use regularization techniques like Ridge or Lasso regression.
    4. Increase sample size to stabilize coefficient estimates.
    5. Check VIF (Variance Inflation Factor) and drop variables with high VIF values.

13. What are some common techniques for transforming categorical variables for use in regression models?
    - Common techniques for transforming categorical variables for regression models are:
    1. Label Encoding – Assigns a unique number to each category.
    2. One-Hot Encoding (Dummy Variables) – Creates binary (0/1) columns for each category.
    3. Ordinal Encoding – Encodes categories based on their order or rank.
    4. Binary Encoding – Converts categories into binary digits (useful for high-cardinality data).
    - These techniques convert categorical data into numerical form so it can be used in regression models.

14. What is the role of interaction terms in Multiple Linear Regression?
    - Interaction terms in Multiple Linear Regression capture the effect of one independent variable on the dependent variable depending on the value of another independent variable.
    - They help model situations where the combined influence of variables is not simply additive, improving model accuracy and interpretation.

15. How can the interpretation of intercept differ between Simple and Multiple Linear Regression?
    - In Simple Linear Regression, the intercept represents the expected value of the dependent variable when the single independent variable is zero.
    - In Multiple Linear Regression, the intercept represents the expected value of the dependent variable when all independent variables are zero, which may be less meaningful or unrealistic in many real-world situations.

16. What is the significance of the slope in regression analysis, and how does it affect predictions?
    - In regression analysis, the slope represents the rate of change of the dependent variable (Y) with respect to the independent variable (X)- Significance:
    1. Indicates the direction of the relationship: Positive slope → Y increases as X increases, Negative slope → Y decreases as X increases
    2. Measures the strength of influence of X on Y
    - Effect on predictions:
    1. Determines how much Y changes for a unit change in X
    2. Larger absolute slope → bigger impact of X on predicted Y.

17. How does the intercept in a regression model provide context for the relationship between variables?
    - The intercept in a regression model provides the baseline value of the dependent variable (Y) when all independent variables (X) are zero.- Context it provides:
    1. Acts as a starting point for predictions.
    2. Helps understand the value of Y without any influence from predictors.
    3. Gives perspective on the relative contribution of each independent variable when combined with slopes.

18. What are the limitations of using R² as a sole measure of model performance?
    - The limitations of using R² as the sole measure of model performance are:
    1. Does not indicate causation – High R² doesn’t mean X causes Y.
    2. Ignores overfitting – Adding more variables can increase R² even if they are irrelevant.
    3. Doesn’t reflect prediction accuracy – A high R² doesn’t guarantee good predictions on new data.
    4. Insensitive to model bias – A model can have high R² but still have biased predictions.
    5. Not useful for non-linear relationships – R² assumes linearity; it may mislead if the relationship is non-linear.

19. How would you interpret a large standard error for a regression coefficient?
    - A large standard error for a regression coefficient indicates that the estimate of the coefficient is imprecise.
    - Interpretation:
    1. The coefficient may vary widely if the model were repeated on different samples.
    2. It reduces the statistical significance of the coefficient (harder to reject null hypothesis).
    3. Could suggest high variability in the data or multicollinearity among predictors.

20. How can heteroscedasticity be identified in residual plots, and why is it important to address it?
    - Heteroscedasticity appears in residual plots when the spread of residuals increases or decreases with fitted values (e.g., funnel shape). It’s important to address because it violates regression assumptions, leading to inefficient estimates and unreliable hypothesis tests.

21. What does it mean if a Multiple Linear Regression model has a high R² but low adjusted R²?
    - It means the model explains much of the variance in the data, but may include unnecessary predictors. Adjusted R² penalizes extra variables, so a large difference indicates overfitting.

22. Why is it important to scale variables in Multiple Linear Regression?
    - Scaling ensures variables with different units or ranges contribute equally, improves numerical stability, and helps algorithms (like gradient-based optimizers) converge faster.

23. What is polynomial regression?
    - Polynomial regression is a type of regression where the relationship between the independent and dependent variable is modeled as a polynomial (e.g., 𝑦=𝑎+𝑏𝑥+𝑐𝑥2+…+…) to capture non-linear patterns.

24. How does polynomial regression differ from linear regression?
    - Linear regression models a straight-line relationship between variables, while polynomial regression models a curved (non-linear) relationship using higher-degree terms of the predictors.

25. When is polynomial regression used?
    - Polynomial regression is used when the relationship between independent and dependent variables is non-linear and cannot be captured well by a straight line.

26. What is the general equation for polynomial regression?
    - The general equation is: y=β0​+β1​x+β2​x2+β3​x3+⋯+βn​xn+ε
    - where 𝑛 n is the degree of the polynomial, 𝛽 β are coefficients, and 𝜀 ε is the error term.

27. Can polynomial regression be applied to multiple variables?
    - Yes, it can. For multiple variables, polynomial terms of each predictor and their interactions can be included to model non-linear relationships.

28. What are the limitations of polynomial regression?
    - Limitations of polynomial regression:
    1. Prone to overfitting with high-degree polynomials.
    2. Sensitive to outliers.
    3. Hard to interpret coefficients for higher degrees.
    4. Can cause numerical instability for large datasets.

29. What methods can be used to evaluate model fit when selecting the degree of a polynomial?
    - Methods to evaluate model fit:
    1. R² and Adjusted R² – measure explained variance.
    2. Mean Squared Error (MSE) / RMSE – measure prediction error.
    3. Cross-validation – checks performance on unseen data.
    4. Residual plots – inspect patterns for underfitting or overfitting.

30. Why is visualization important in polynomial regression?
    - Visualization helps to see the non-linear relationship, check model fit, and detect underfitting or overfitting in polynomial regression.

In [ ]:
#Q31. How is polynomial regression implemented in Python?
#Ans. In Python, polynomial regression is implemented using PolynomialFeatures from sklearn.preprocessing to create polynomial terms, then fitting a LinearRegression model on these transformed features.

from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
import numpy as np

# Sample data for demonstration
X = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]).reshape(-1, 1) # Independent variable
y = np.array([2, 5, 6, 7, 8, 9, 10, 12, 15, 18]) # Dependent variable

poly = PolynomialFeatures(degree=2)
X_poly = poly.fit_transform(X)
model = LinearRegression().fit(X_poly, y)

print("Polynomial features transformed (first 5 rows):\n", X_poly[:5])
print("Model coefficients:", model.coef_)
print("Model intercept:", model.intercept_)

Polynomial features transformed (first 5 rows):
 [[ 1.  1.  1.]
 [ 1.  2.  4.]
 [ 1.  3.  9.]
 [ 1.  4. 16.]
 [ 1.  5. 25.]]
Model coefficients: [0.         0.58106061 0.08712121]
Model intercept: 2.650000000000002
